import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service | Aaron Technologies",
  description: "Review the business and sourcing terms of service for contracting with Aaron Technologies Inc.",
};

export default function TermsPage() {
  return (
    <>
      {/* Hero Section */}
      <section className="section-dark relative overflow-hidden border-b border-navy-850">
        <div
          className="absolute inset-0 opacity-[0.02] pointer-events-none"
          style={{
            backgroundImage: `linear-gradient(rgba(199,91,42,0.3) 1px, transparent 1px),
              linear-gradient(90deg, rgba(199,91,42,0.3) 1px, transparent 1px)`,
            backgroundSize: "40px 40px",
          }}
        />
        <div className="relative max-w-7xl mx-auto px-6 py-16">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-steel-400 hover:text-steel-200 transition-colors mb-6"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Link>
          <div className="max-w-3xl">
            <h1 className="font-heading font-bold text-3xl sm:text-4xl text-white mb-3">
              Terms of Service
            </h1>
            <p className="text-steel-400 text-sm">
              Last updated: June 25, 2026
            </p>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="bg-steel-100 py-16 md:py-20">
        <div className="max-w-4xl mx-auto px-6 bg-white border border-steel-300 p-8 sm:p-12 md:p-16 space-y-10">
          <div className="flex items-center gap-3 pb-5 border-b border-steel-200">
            <FileText className="w-8 h-8 text-copper-500 shrink-0" />
            <p className="text-sm font-semibold text-navy-900 leading-relaxed">
              Welcome to Aaron Technologies Inc. By accessing our website, using our landed-cost tools, or requesting sourcing quotes, you agree to comply with the following terms.
            </p>
          </div>

          <div className="space-y-6">
            <h2 className="text-xl font-heading font-bold text-navy-900">
              1. Sourcing Specifications & Drawings
            </h2>
            <p className="text-steel-700 text-sm sm:text-base leading-relaxed">
              When submitting RFQ files, CAD drawings, or engineering specifications:
            </p>
            <ul className="list-disc list-inside space-y-2 text-steel-700 text-sm sm:text-base pl-4">
              <li>You warrant that you possess all intellectual property rights to the drawings and that sharing them does not violate third-party agreements.</li>
              <li>You are solely responsible for verifying that the drawings contain all necessary tolerances, dimensions, material grades, and testing specifications.</li>
            </ul>
          </div>

          <div className="space-y-6">
            <h2 className="text-xl font-heading font-bold text-navy-900">
              2. Sourcing Estimates & Landed Costs
            </h2>
            <p className="text-steel-700 text-sm sm:text-base leading-relaxed">
              Any outputs generated by the <strong>Landed Cost Calculator</strong> on this website are for estimation purposes only. Live commercial quotes are subject to final review of tolerances, quantities, ocean freight indices, and specific alloy raw material market rates at the time of quotation.
            </p>
          </div>

          <div className="space-y-6">
            <h2 className="text-xl font-heading font-bold text-navy-900">
              3. Quality Assurance & Certifications
            </h2>
            <p className="text-steel-700 text-sm sm:text-base leading-relaxed">
              Aaron Technologies Inc. guarantees that all supplied materials conform to the agreed-upon standards (e.g. ASTM, ASME, ISO, DIN) as documented on the Mill Test Certificates (MTCs). Our liability for non-conforming goods is governed strictly by the terms laid out in the final domestic purchase order contract between you and Aaron Technologies Inc.
            </p>
          </div>

          <div className="space-y-6">
            <h2 className="text-xl font-heading font-bold text-navy-900">
              4. Governing Law & Jurisdiction
            </h2>
            <p className="text-steel-700 text-sm sm:text-base leading-relaxed">
              Aaron Technologies Inc. is a US-incorporated entity. Any legal claims, transactions, or disputes arising from your use of this website or procurement contracts are governed exclusively by the laws of the State of New Jersey, United States.
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
