import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service | Aaron Technologies",
  description: "Review the business and sourcing terms of service for contracting with Aaron Technologies Inc.",
};

export default function TermsPage() {
  return (
    <>
      {/* Hero */}
      <section className="border-b border-border">
        <div className="max-w-[1360px] mx-auto px-6 pt-20 pb-12 md:pt-28 md:pb-16">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-sm text-text-tertiary hover:text-text-primary transition-colors mb-6"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Back to Home
          </Link>
          <h1 className="text-3xl sm:text-4xl leading-tight mb-2">
            Terms of <strong>Service</strong>
          </h1>
          <p className="text-sm text-text-tertiary">
            Last updated: June 25, 2026
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 md:py-20">
        <div className="max-w-3xl mx-auto px-6 space-y-10">
          <div className="flex items-center gap-3 pb-5 border-b border-border">
            <FileText className="w-6 h-6 text-primary-muted shrink-0" />
            <p className="text-sm font-medium text-text-primary leading-relaxed">
              Welcome to Aaron Technologies Inc. By accessing our website, using our landed-cost tools, or requesting sourcing quotes, you agree to comply with the following terms.
            </p>
          </div>

          <div className="space-y-6">
            <h2 className="text-xl text-text-primary">
              1. Sourcing Specifications & Drawings
            </h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              When submitting RFQ files, CAD drawings, or engineering specifications:
            </p>
            <ul className="list-disc list-inside space-y-2 text-text-secondary text-sm pl-4">
              <li>You warrant that you possess all intellectual property rights to the drawings and that sharing them does not violate third-party agreements.</li>
              <li>You are solely responsible for verifying that the drawings contain all necessary tolerances, dimensions, material grades, and testing specifications.</li>
            </ul>
          </div>

          <div className="space-y-6">
            <h2 className="text-xl text-text-primary">
              2. Sourcing Estimates & Landed Costs
            </h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              Any outputs generated by the <strong className="text-text-primary">Landed Cost Calculator</strong> on this website are for estimation purposes only. Live commercial quotes are subject to final review of tolerances, quantities, ocean freight indices, and specific alloy raw material market rates at the time of quotation.
            </p>
          </div>

          <div className="space-y-6">
            <h2 className="text-xl text-text-primary">
              3. Quality Assurance & Certifications
            </h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              Aaron Technologies Inc. guarantees that all supplied materials conform to the agreed-upon standards (e.g. ASTM, ASME, ISO, DIN) as documented on the Mill Test Certificates (MTCs). Our liability for non-conforming goods is governed strictly by the terms laid out in the final domestic purchase order contract between you and Aaron Technologies Inc.
            </p>
          </div>

          <div className="space-y-6">
            <h2 className="text-xl text-text-primary">
              4. Governing Law & Jurisdiction
            </h2>
            <p className="text-text-secondary text-sm leading-relaxed">
              Aaron Technologies Inc. is a US-incorporated entity. Any legal claims, transactions, or disputes arising from your use of this website or procurement contracts are governed exclusively by the laws of the State of New Jersey, United States.
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
